### ISSUE TITLE
testNetworks

### ISSUE THREAD

**Issue by judytabbal** [georgeoneill/dynets#1]
Hello,
thank you for this interesting work !
Can you please add the code of testNetworks using the second method which is the Xonset null distribution as explained in the article. The code include the Xflip method only.
Best regards!

**Comment by georgeoneill** [comment]
HI Judy,

It certainly could be added, I just need a bit of time to test it (I've moved labs so data needs to be migrated for me to confirm it works).

**Comment by georgeoneill** [comment]
Hi Judy,

Apologies for the delay, but this functionality has been implemented and lightly tested. I'll close issue this for now, but if there are any problems or some instructions are needed feel free to reopen it. 

G

**Comment by judytabbal** [comment]
Hello,
Thank you so much !!

________________________________
